version: '3.8'

services:
  mysql:
    image: mariadb:10.4.32
    container_name: crm_mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}_ROOT
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ./database/crm_system.sql:/docker-entrypoint-initdb.d/02-crm_system.sql:ro
      - ./database/migrations:/docker-entrypoint-initdb.d/migrations:ro
    ports:
      - "3306:3306"
    command: --innodb-buffer-pool-size=128M --max-connections=50
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - crm_network

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: crm_nextjs
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NODE_OPTIONS: --max-old-space-size=512
    volumes:
      # Mount uploads directory for file storage
      - ./uploads:/app/uploads
      - ./public/uploads:/app/public/uploads
    depends_on:
      - mysql
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    networks:
      - crm_network

  # phpMyAdmin - Hidden and Secured
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.2
    container_name: crm_phpmyadmin
    env_file:
      - .env
    environment:
      PMA_HOST: crm_mysql
      PMA_PORT: 3306
      PMA_USER: ${DATABASE_USER}
      PMA_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}_ROOT
      PMA_ABSOLUTE_URI: "https://crm.robintejarat.com/secure-db-admin-panel-x7k9m2/"
      # Security settings
      PMA_CONTROLUSER: ${DATABASE_USER}
      PMA_CONTROLPASS: ${DATABASE_PASSWORD}
      # Hide phpMyAdmin version
      HIDE_PHP_VERSION: 1
    restart: unless-stopped
    expose:
      - "80"
    depends_on:
      - mysql
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    networks:
      - crm_network

  nginx:
    image: nginx:alpine
    container_name: crm_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - nextjs
      - phpmyadmin
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    networks:
      - crm_network

volumes:
  mysql_data:
    driver: local

networks:
  crm_network:
    driver: bridge