version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: crm_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ./database/crm_system.sql:/docker-entrypoint-initdb.d/02-crm_system.sql:ro
      - ./database/migrations:/docker-entrypoint-initdb.d/migrations:ro
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=128M --max-connections=50
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - crm_network

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: crm_nextjs
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NODE_OPTIONS=--max-old-space-size=512
    depends_on:
      - mysql
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    networks:
      - crm_network

  # phpMyAdmin - Hidden and Secured
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: crm_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_ABSOLUTE_URI: "https://crm.robintejarat.com/secure-db-admin-panel-x7k9m2/"
      # Security settings
      PMA_CONTROLUSER: ${MYSQL_USER}
      PMA_CONTROLPASS: ${MYSQL_PASSWORD}
      # Hide phpMyAdmin version
      HIDE_PHP_VERSION: 1
    restart: unless-stopped
    expose:
      - "80"
    depends_on:
      - mysql
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    networks:
      - crm_network

  nginx:
    image: nginx:alpine
    container_name: crm_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - nextjs
      - phpmyadmin
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    networks:
      - crm_network

volumes:
  mysql_data:
    driver: local

networks:
  crm_network:
    driver: bridge