version: '3.8'

services:
  # Next.js Application - Memory Optimized
  nextjs:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_OPTIONS=--max-old-space-size=384
    container_name: crm-nextjs
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - NODE_OPTIONS=--max-old-space-size=256
      - DATABASE_HOST=${DATABASE_HOST:-mysql}
      - DATABASE_USER=${DATABASE_USER:-crm_app_user}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME:-crm_system}
      - DATABASE_URL=${DATABASE_URL}
      - AUDIO_ENABLED=false
      - VPS_MODE=true
      - FALLBACK_TO_MANUAL_INPUT=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:3000"]
      interval: 60s
      timeout: 15s
      retries: 2
      start_period: 60s
    depends_on:
      mysql:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    networks:
      - crm-network

  # MySQL Database - Memory Optimized
  mysql:
    image: mysql:8.0
    container_name: crm-mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}_ROOT"
      MYSQL_DATABASE: "${DATABASE_NAME:-crm_system}"
      MYSQL_USER: "${DATABASE_USER:-crm_app_user}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    restart: unless-stopped
    command: >
      --default-authentication-plugin=mysql_native_password 
      --innodb-buffer-pool-size=128M 
      --max-connections=50
      --innodb-log-file-size=32M
      --innodb-flush-log-at-trx-commit=2
      --query-cache-size=0
      --query-cache-type=0
      --performance-schema=OFF
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DATABASE_PASSWORD}_ROOT"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    networks:
      - crm-network

  # phpMyAdmin - Minimal
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: crm-phpmyadmin
    env_file:
      - .env
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: "${DATABASE_USER:-crm_app_user}"
      PMA_PASSWORD: "${DATABASE_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}_ROOT"
      PMA_ABSOLUTE_URI: "${NEXTAUTH_URL}/secure-db-admin-panel-x7k9m2/"
      HIDE_PHP_VERSION: 1
      MEMORY_LIMIT: 64M
    restart: unless-stopped
    expose:
      - "80"
    depends_on:
      mysql:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'
        reservations:
          memory: 64M
          cpus: '0.1'
    networks:
      - crm-network

  # Nginx - Minimal
  nginx:
    image: nginx:alpine
    container_name: crm-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/active.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    restart: unless-stopped
    depends_on:
      - nextjs
      - phpmyadmin
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.25'
        reservations:
          memory: 32M
          cpus: '0.1'
    networks:
      - crm-network

volumes:
  mysql_data:
    driver: local

networks:
  crm-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450